set -e
set +x

JDK_14_VERSION_NUMBER=30
JDK_14_VERSION=openjdk-14-ea+${JDK_14_VERSION_NUMBER}_windows-x64_bin.zip

JDK_14_EXTRACTED_PATH=jdk-14
rm -rf ./${JDK_14_EXTRACTED_PATH}
unzip ${JDK_14_VERSION}

