version: 2.1

jobs:
  build-mac:
    macos:
      xcode: 11.2.0

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            HOMEBREW_NO_AUTO_UPDATE=1 brew install wget

      - run:
          name: Run build
          command: |
            ./install_corretto_jdk_osx.sh
            ./install_maven_osx.sh
            ./download_jdk_osx.sh
            ./package_osx.sh

      - store_artifacts:
          path: ./target/jpackage-app/WereKitten-1.0.pkg
          destination: WereKitten-1.0.pkg

  build-windows:
    machine:
      image: "windows-server-2019-vs2019:stable"
      resource_class: "windows.medium"
      shell: bash.exe
    steps:
      - checkout

      - restore_cache:
          keys:
            - circle-packages-{{ checksum ".circleci/config.yml" }}

      - run:
          name: Install nuget dependencies
          command: |
            nuget install WiX.Toolset -Version 3.9.1208.0

      - run:
          name: Install chocolatey dependencies
          command: |
            choco install maven --version 3.6.2
            choco install correttojdk wget

      - run:
          name: Download experimental JDK with jpackage in it
          command: ./download_jdk_win64.sh

      - save_cache:
          paths:
            - jdk-14
          key: circle-packages-{{ checksum ".circleci/config.yml" }}

      - run:
          name: Build app + installer
          command: |
            export PATH=/c/Users/circleci/project/Wix.Toolset.3.9.1208.0/tools/wix:$PATH
            ./package_win64.sh

      - store_artifacts:
          path: .\target\jpackage-app\WereKitten-1.0.msi
          destination: WereKitten-1.0.msi

workflows:
  version: 2
  build_all:
    jobs:
      - build-mac
      - build-windows

