version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: bash.exe
    steps:
      - checkout

      - restore_cache:
          keys:
            - circle-packages-{{ checksum ".circleci/config.yml" }}

      - run:
          name: Install dependencies
          command: |
            choco install maven correttojdk wget
            ./download_jdk_win64.sh

      - save_cache:
          paths:
            - jdk-14
          key: circle-packages-{{ checksum ".circleci/config.yml" }}

      - run:
          name: Build app + installer
          command: ./package_win64.sh
