version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: bash.exe
    steps:
      - checkout

      - restore_cache:
          keys:
            - circle-packages-{{ checksum ".circleci/config.yml" }}

      - run:
          name: Install chocolatey dependencies
          command: choco install maven correttojdk wget

      - run:
          name: Download experimental JDK with jpackage in it
          command: ./download_jdk_win64.sh

      - save_cache:
          paths:
            - jdk-14
          key: circle-packages-{{ checksum ".circleci/config.yml" }}

      - run:
          name: Build app + installer
          command: |
            function mvn {
                /c/ProgramData/chocolatey/lib/maven/apache-maven-3.6.2/bin/mvn
            }
           ./package_win64.sh
