version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: bash.exe
    steps:
      - checkout

      - restore_cache:
          keys:
            - circle-packages-{{ checksum ".circleci/config.yml" }}

      - run:
          name: Install chocolatey dependencies
          command: |
            choco install maven --version 3.6.2
            choco install correttojdk wget wixtoolset

      - run:
          name: Download experimental JDK with jpackage in it
          command: ./download_jdk_win64.sh

      - save_cache:
          paths:
            - jdk-14
          key: circle-packages-{{ checksum ".circleci/config.yml" }}

      - run:
          name: Build app + installer
          command: ./package_win64.sh

      - store_artifacts:
          path: .\target\jpackage-app\WereKitten-1.0.msi
