version: 2

release-filters: &release-filters
  filters:
    tags:
      only: /^v\d+\.\d+\.\d+$/
    branches:
      ignore: /.*/

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch

    steps:
      - checkout

      - run: |
          echo "Tag: ${CIRCLE_TAG}"
          echo "Tag from git: $(git tag -l --points-at HEAD)"

      - restore_cache:
          key: circleci-werekitten-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: circleci-werekitten-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

  build-mac-installer:
    macos:
      xcode: 11.2.0

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            HOMEBREW_NO_AUTO_UPDATE=1 brew install wget

      - run:
          name: Run build
          command: |
            ./install_corretto_jdk_osx.sh
            ./install_maven_osx.sh
            ./download_jdk_osx.sh
            ./package_osx.sh

      - store_artifacts:
          path: ./target/jpackage-app/WereKitten-1.0.pkg
          destination: WereKitten-1.0.pkg

      - persist_to_workspace:
          root: ~/
          paths: project/target/jpackage-app/WereKitten-1.0.pkg

  build-windows-installer:
    machine:
      image: "windows-server-2019-vs2019:stable"
      resource_class: "windows.medium"
      shell: bash.exe
    steps:
      - checkout

      - restore_cache:
          keys:
            - circle-packages-{{ checksum ".circleci/config.yml" }}

      - run:
          name: Install nuget dependencies
          command: |
            nuget install WiX.Toolset -Version 3.9.1208.0

      - run:
          name: Install chocolatey dependencies
          command: |
            choco install maven --version 3.6.2
            choco install correttojdk wget

      - run:
          name: Download experimental JDK with jpackage in it
          command: ./download_jdk_win64.sh

      - save_cache:
          paths:
            - jdk-14
          key: circle-packages-{{ checksum ".circleci/config.yml" }}

      - run:
          name: Build app + installer
          command: |
            export PATH=/c/Users/circleci/project/Wix.Toolset.3.9.1208.0/tools/wix:$PATH
            ./package_win64.sh

      - store_artifacts:
          path: .\target\jpackage-app\WereKitten-1.0.msi
          destination: WereKitten-1.0.msi

      - run:
          name: Test installer
          shell: powershell.exe
          command: |
            Start-Process msiexec.exe -Wait -ArgumentList '/I C:\Users\circleci\project\target\jpackage-app\WereKitten-1.0.msi /quiet /L*V msilog.txt'
            if(![System.IO.File]::Exists('C:\Program Files\WereKitten\WereKitten.exe')){throw (New-Object System.IO.FileNotFoundException("Installed file not found!"))}

      - store_artifacts:
          path: msilog.log
          destination: msilog.log

      - persist_to_workspace:
          root: ~/
          paths: project\target\jpackage-app\WereKitten-1.0.msi

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} \
                -u ${CIRCLE_PROJECT_USERNAME} \
                -r ${CIRCLE_PROJECT_REPONAME} \
                -c ${CIRCLE_SHA1} \
                -delete \
                -n "Alpha Release ${CIRCLE_TAG}" \
                -b "This is a release for alpha testers to try our game!" \
                "${CIRCLE_TAG}" \
                "./artifacts/"


workflows:
  version: 2
  build_release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - build-mac-installer:
          <<: *release-filters
          requires:
            - build
      - build-windows-installer:
          <<: *release-filters
          requires:
            - build
      - publish-github-release:
          <<: *release-filters
          requires:
            - build-mac-installer
            - build-windows-installer
