version: 2.1

#orbs:
#  win: circleci/windows@1.0.0

jobs:
  build-mac:
    macos:
      xcode: "9.0"

    steps:
      - checkout

      - run:
          name: Run build
          command: |
            ./download_jdk_osx.sh
            ./package_osx.sh
#
#  build-windows:
#    executor:
#      name: win/vs2019
#      shell: bash.exe
#    steps:
#      - checkout
#
#      - restore_cache:
#          keys:
#            - circle-packages-{{ checksum ".circleci/config.yml" }}
#
#      - run:
#          name: Install chocolatey dependencies
#          command: |
#            choco install maven --version 3.6.2
#            choco install correttojdk wget
#
#      - run:
#          name: Install wixtoolset without the .NET framework dependency
#          command: |
#            wget https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip
#            unzip wix311-binaries.zip
#            ls
#
#      - run:
#          name: Download experimental JDK with jpackage in it
#          command: ./download_jdk_win64.sh
#
#      - save_cache:
#          paths:
#            - jdk-14
#          key: circle-packages-{{ checksum ".circleci/config.yml" }}
#
#      - run:
#          name: Build app + installer
#          command: ./package_win64.sh
#
#      - store_artifacts:
#          path: .\target\jpackage-app\WereKitten-1.0.msi

workflows:
  version: 2
  build_all:
    jobs:
      - build-mac
#      - build-windows

